
import java.io.IOException;
import javax.swing.JFrame;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONObject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Home
 */
public class Setup_Frame extends javax.swing.JFrame {
    String uname="", pwd="";
    /**
     * Creates new form Setup_Frame
     */
    public Setup_Frame() throws IOException {
        initComponents();
        JSON_manager jm = new JSON_manager();
        if(jm.checkJSON()){
                JSONObject jo = jm.readJSON();
                JSONObject sq = jo.getJSONObject("MySQL");
                uname = jo.getString("uname");
                pwd = jo.getString("pwd");
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Install_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mu_tf = new javax.swing.JTextField();
        Pro_btn = new javax.swing.JButton();
        mp_pf = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("If facing problems check whether MySQL is installled or not.");

        Install_btn.setText("Install MySQL");
        Install_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Install_btnActionPerformed(evt);
            }
        });

        jLabel2.setText("MySQL Username :");

        jLabel3.setText("MySQL Password :");

        Pro_btn.setText("Proceed");
        Pro_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pro_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(Install_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(mu_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(mp_pf, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(Pro_btn)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Install_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mu_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mp_pf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(Pro_btn)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Pro_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pro_btnActionPerformed
if(!"".equals(uname)){
    mu_tf.setText(uname);
    mp_pf.setText(pwd);
}
String sqluser=mu_tf.getText();
String sqlpwd = mp_pf.getText();
String c="jdbc:mysql://localhost:3306/";
JSON_manager jm = new JSON_manager();
Connection conn=null;
Connection conn2=null;
        try {
            conn=DriverManager.getConnection(c,sqluser,sqlpwd);
            System.out.println("...Connected...");
            if(jm.checkJSON()){
                JSONObject jo = jm.readJSON();
            }
            else{
                jm.writeJSON(sqluser, sqlpwd);
            }
            Statement s=(Statement)conn.createStatement();
            String q="create database if not exists TeachersApp;";
            s.executeUpdate(q);
            String c2="jdbc:mysql://localhost:3306/TeachersApp";
            conn2=DriverManager.getConnection(c2,sqluser,sqlpwd);
            Statement s2=(Statement)conn2.createStatement();
            q="create table if not exists student(Roll_No int(3),Name char(30),Marks_in_CSc int(3));";
            s2.executeUpdate(q);
        } catch (SQLException e) {
            System.out.println(e);
        } catch (IOException ex) {
            Logger.getLogger(Setup_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
JFrame Login_Frame = new JFrame();
this.setVisible(false);
new Login_Frame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_Pro_btnActionPerformed

    private void Install_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Install_btnActionPerformed
String url="https://dev.mysql.com/downloads/";
        try { 
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_Install_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setup_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setup_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setup_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setup_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Setup_Frame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Setup_Frame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Install_btn;
    private javax.swing.JButton Pro_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField mp_pf;
    private javax.swing.JTextField mu_tf;
    // End of variables declaration//GEN-END:variables
}
